baseurl      = "https://www.gfearzila.pt/" #TODO change this
languageCode = "pt-PT"
title        = "GFE Arzila - Baixo Mondego"
theme        = "hugo-creative-theme"
googleAnalytics = "UA-52628308-2"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  name        = "GFE Arzila"
  description = "Fundado em 24 de Fevereiro de 1974, o Grupo Folclórico e Etnográfico de Arzila, procura transmitir as tradições do povo da sua terra e da sua região."
  socialImage  = "img/header.jpg"

  # The path must be relative to the static folder
  favicon     = "favicon1.ico"

  # Custom CSS
  custom_css = [
    "css/index.css",
    "css/hero.css",
    "css/aside.css",
    "css/nav.css",
    "css/cta-events.css"
  ]

  # Custom JavaScript
  custom_js = ["cta-events.js"]

  #Custom Plugins JavaScript
  plugins_js = []


  # Navigation
  [params.navigation]
    brand = "GFE Arzila"

    [[params.navigation.list]]
      ref = "about"
      text = "Sobre"

    [[params.navigation.list]]
      ref = "portfolio"
      text = "Portfolio"
      scrollOffset = 50

    [[params.navigation.list]]
      ref = "events"
      text = "Eventos"

    [[params.navigation.list]]
      ref = "contact"
      text = "Contactos"

  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan       = "Grupo Folclórico e Etnográfico de Arzila"
    subtitle     = "42 anos em representação dos usos e costumes dos nossos antepassados"
    scrollButton = true

    [params.hero.event]
      helperText = ""
      link = "#"
      title = "43º Aniversário"
      eventDate = "2017/02/24 00:00"
      status = "24 de Fevereiro de 1974"


  # About section
  [params.about]
    headline    = "Sobre"
    description = "<strong><i>[Arzila](//pt.wikipedia.org/wiki/Arzila_(Portugal))</i></strong> é uma pequena freguesia do concelho de Coimbra, situada na margem esquerda do rio Mondego, 13 km a jusante daquela cidade, na denominada região do Baixo Mondego.<BR><BR>Fundado em 24 de Fevereiro de 1974, o <strong><i>Grupo Folclórico e Etnográfico de Arzila</i></strong>, procura transmitir as tradições do povo da sua terra e da sua região. A sua acção de defesa do património tem ido desde a recolha de elementos etnográficos, à realização de debates, jornadas culturais, exposições, recuperação de festas, de jogos e outras tradições que estavam a desaparecer.<BR><BR>Tem sido também sua preocupação a defesa do artesanato, na qual as “esteiras” de Arzila, assumem papel de destaque.<BR><BR>É considerado “Grupo de Interesse Folclórico” pelo Departamento de Cultura da Câmara Municipal de Coimbra, é filiado na Federação do Folclore Português, na Associação de Folclore e Etnografia da Região do Mondego e INATEL e foi declarado Colectividade de Utilidade Pública, em 1990. Em 2003, foi-lhe atribuída pela Câmara Municipal de Coimbra, a “medalha de mérito cultural”."
    buttonText  = "Obter historial"
    externalLink = "files/historial_gfearzila.pdf"
    logo = "img/logos/gfea.png"

  # Service section
  [params.services]
    headline = ""

    [[params.services.list]]
      logo  = "ffp.png"
      title = "Fed. de Folclore Portugues"
      link  = "https://www.ffp.pt/"

    [[params.services.list]]
      logo  = "AFERM.jpg"
      title = "AFERM"
      link  = "http://www.aferm.pt/"

    [[params.services.list]]
      logo  = "inatel.png"
      title = "INATEL"
      link  = "http://www.inatel.pt/"

    [[params.services.list]]
      logo  = "cmc.png"
      title = "Camara Municipal de Coimbra"
      link  = "https://www.cm-coimbra.pt/"

  # Portfolio modals
  [params.portfolio.modal]
    buttonText = " Fechar"

  # Aside section
  [params.events]
    headline = "Eventos"
    description = ""

  # Events modals
  [params.events.modal]
    organizer  = "Organizador"
    date       = "Data"
    buttonText = " Fechar"

  # Contact section
  [params.contact]
    headline    = "Contactos"
    description = "<BR>"
    email       = "gfearzila@gmail.com"

    [params.contact.facebook]
      text = "@gfearzila"
      link = "https://www.facebook.com/gfearzila"

    [params.contact.address]
      address = "Rua do Bairro nº 16, Arzila"
      postalCode = "3045-356 Arzila"
      coord = "40.1838504,-8.554425"

    [params.footer]
      privacyPolicy = "Privacidade"
      licence = "@2017 Grupo Folclórico e Etnográfico de Arzila - Baixo Mondego"
